all:
  hosts:
    prod:
      ansible_host: 192.168.1.36
      ansible_connection: ssh
      ansible_user: semo
  # children:
  #   environments:
  #     hosts:
  #       foo.example.com:
  #       bar.example.com: